name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy Maven Repositories
        run: bash maven-copy.sh

      - name: Show Maven Files
        run: find maven -type f

      - name: Show Maven Jars
        run: find maven -type f | grep -E '\.jar$' | xargs -n 100 ls -lh

      - name: Build Shadow Jar
        run: bash gradlew shadowJar

      - name: Show Shadow Jar
        run: find build/libs -type f

      - name: Test
        run: |
          command=(java -cp build/libs/java-kotlin-project-sample-all.jar Main)
          out=$("${command[@]}")
          echo "$out"
          [ 'KOTLIN[Hello from Java!]' = "$out" ] || exit

          command=(java -cp build/libs/java-kotlin-project-sample-all.jar MainKotlin)
          out=$("${command[@]}")
          echo "$out"
          [ 'JAVA[Hello from Kotlin!]' = "$out" ] || exit
